#!/usr/bin/env bun
// This emitter reads only Spec Data Files, independently of either Core.
import { resolve } from 'node:path';
import machine from '../../spec/data/machine.toml';
import costs from '../../spec/data/costs.toml';
import errors from '../../spec/data/errors.toml';
import diagnostics from '../../spec/data/diagnostics.toml';
import limits from '../../spec/data/limits.toml';
import units from '../../spec/data/units.toml';
import version from '../../spec/data/version.toml';
import grammar from '../../spec/data/grammar.toml';
import stdlib from '../../spec/data/stdlib.toml';
import { formatGo, writeOutput } from './output';

type Shape =
  | { kind: 'scalar'; type: string }
  | { item: Shape; kind: 'array' }
  | { fields: [string, Shape][]; kind: 'struct'; name: string };
const identifier = (name: string) =>
  name.replaceAll(/(^|[^\dA-Za-z]+)([\dA-Za-z])/g, (_, __, c: string) =>
    c.toUpperCase(),
  );
const infer = (values: unknown[], name: string): Shape => {
  const kinds = new Set(
    values.map(value => (Array.isArray(value) ? 'array' : typeof value)),
  );
  if (kinds.size > 1) {
    // Instruction pops/pushes are an integer or a normative formula.
    return { kind: 'scalar', type: 'any' };
  }
  if (kinds.has('array')) {
    return { kind: 'array', item: infer(values.flat(), `${name}Entry`) };
  }
  if (kinds.has('object')) {
    const objects = values as Record<string, unknown>[];
    const keys = [...new Set(objects.flatMap(Object.keys))];
    return {
      kind: 'struct',
      name,
      fields: keys.map(key => [
        key,
        infer(
          objects.filter(value => key in value).map(value => value[key]),
          name + identifier(key),
        ),
      ]),
    };
  }
  return {
    kind: 'scalar',
    type: kinds.has('number')
      ? 'int64'
      : kinds.has('boolean')
        ? 'bool'
        : 'string',
  };
};
const typeName = (shape: Shape): string =>
  shape.kind === 'scalar'
    ? shape.type
    : shape.kind === 'array'
      ? `[]${typeName(shape.item)}`
      : shape.name;
const literal = (value: unknown, shape: Shape): string => {
  if (shape.kind === 'scalar') {
    return JSON.stringify(value);
  }
  if (shape.kind === 'array') {
    return `${typeName(shape)}{\n${(value as unknown[])
      .map(entry => `${literal(entry, shape.item)},\n`)
      .join('')}}`;
  }
  const object = value as Record<string, unknown>;
  return `${shape.name}{\n${shape.fields
    .filter(([key]) => key in object)
    .map(
      ([key, field]) => `${identifier(key)}: ${literal(object[key], field)},\n`,
    )
    .join('')}}`;
};

export const emitCatalogue = (
  name: string,
  data: unknown,
  sourceName = name,
): string => {
  const publicName = identifier(name);
  const shape = infer([data], `${publicName}Table`);
  const declarations: string[] = [];
  const declare = (item: Shape) => {
    if (item.kind === 'array') {
      declare(item.item);
    } else if (item.kind === 'struct') {
      declarations.push(
        `type ${item.name} struct {\n${item.fields
          .map(([key, field]) => `${identifier(key)} ${typeName(field)}\n`)
          .join('')}}\n`,
      );
      item.fields.forEach(([, field]) => declare(field));
    }
  };
  declare(shape);
  return formatGo(
    `// Code generated by tools/go/generate.ts from spec/data/${sourceName}.toml; DO NOT EDIT.\n` +
      `package generated\n\n${declarations.join('\n')}\n` +
      `var ${publicName} = ${literal(data, shape)}\n`,
  );
};

export const generateGoCatalogues = async (check: boolean): Promise<void> => {
  for (const [name, data] of Object.entries({
    machine,
    costs,
    errors,
    diagnostics,
    limits,
    units,
    version,
    grammar,
    builtins: { builtin: stdlib.builtin },
  })) {
    await writeOutput(
      resolve(import.meta.dir, `../../impl/go/internal/generated/${name}.go`),
      emitCatalogue(name, data, name === 'builtins' ? 'stdlib' : name),
      check,
      'bun run go:generate',
    );
  }
};

if (import.meta.main) {
  if (Bun.argv.slice(2).some(arg => arg !== '--check')) {
    throw new Error('Usage: bun tools/go/generate.ts [--check]');
  }
  await generateGoCatalogues(Bun.argv.includes('--check'));
}
