#!/usr/bin/env bun
// This emitter reads Spec Data Files and Standard Library sources, independently of either Core.
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import machine from '../../spec/data/machine.toml';
import costs from '../../spec/data/costs.toml';
import errors from '../../spec/data/errors.toml';
import diagnostics from '../../spec/data/diagnostics.toml';
import limits from '../../spec/data/limits.toml';
import units from '../../spec/data/units.toml';
import version from '../../spec/data/version.toml';
import corpus from '../../spec/data/corpus.toml';
import grammar from '../../spec/data/grammar.toml';
import stdlib from '../../spec/data/stdlib.toml';
import { compileCostModel, type CompiledCostModel } from '../costs/compile';
import { formatGo, writeOutput } from './output';

type Shape =
  | { kind: 'scalar'; type: string }
  | { item: Shape; kind: 'array' }
  | { fields: [string, Shape][]; kind: 'struct'; name: string };
const identifier = (name: string) =>
  name.replaceAll(/(^|[^\dA-Za-z]+)([\dA-Za-z])/g, (_, __, c: string) =>
    c.toUpperCase(),
  );
const infer = (values: unknown[], name: string): Shape => {
  const kinds = new Set(
    values.map(value => (Array.isArray(value) ? 'array' : typeof value)),
  );
  if (kinds.size > 1) {
    // Instruction pops/pushes are an integer or a normative formula.
    return { kind: 'scalar', type: 'any' };
  }
  if (kinds.has('array')) {
    return { kind: 'array', item: infer(values.flat(), `${name}Entry`) };
  }
  if (kinds.has('object')) {
    const objects = values as Record<string, unknown>[];
    const keys = [...new Set(objects.flatMap(Object.keys))];
    return {
      kind: 'struct',
      name,
      fields: keys.map(key => [
        key,
        infer(
          objects.filter(value => key in value).map(value => value[key]),
          name + identifier(key),
        ),
      ]),
    };
  }
  return {
    kind: 'scalar',
    type: kinds.has('number')
      ? 'int64'
      : kinds.has('boolean')
        ? 'bool'
        : 'string',
  };
};
const typeName = (shape: Shape): string =>
  shape.kind === 'scalar'
    ? shape.type
    : shape.kind === 'array'
      ? `[]${typeName(shape.item)}`
      : shape.name;
const literal = (value: unknown, shape: Shape): string => {
  if (shape.kind === 'scalar') {
    return JSON.stringify(value);
  }
  if (shape.kind === 'array') {
    return `${typeName(shape)}{\n${(value as unknown[])
      .map(entry => `${literal(entry, shape.item)},\n`)
      .join('')}}`;
  }
  const object = value as Record<string, unknown>;
  return `${shape.name}{\n${shape.fields
    .filter(([key]) => key in object)
    .map(
      ([key, field]) => `${identifier(key)}: ${literal(object[key], field)},\n`,
    )
    .join('')}}`;
};

export const emitCatalogue = (
  name: string,
  data: unknown,
  sourceName = name,
): string => {
  const publicName = identifier(name);
  const shape = infer([data], `${publicName}Table`);
  const declarations: string[] = [];
  const declare = (item: Shape) => {
    if (item.kind === 'array') {
      declare(item.item);
    } else if (item.kind === 'struct') {
      declarations.push(
        `type ${item.name} struct {\n${item.fields
          .map(([key, field]) => `${identifier(key)} ${typeName(field)}\n`)
          .join('')}}\n`,
      );
      item.fields.forEach(([, field]) => declare(field));
    }
  };
  declare(shape);
  return formatGo(
    `// Code generated by tools/go/generate.ts from spec/data/${sourceName}.toml; DO NOT EDIT.\n` +
      `package generated\n\n${declarations.join('\n')}\n` +
      `var ${publicName} = ${literal(data, shape)}\n`,
  );
};

// An Opcode is an instruction's index in the machine table. Interpreter loops
// dispatch on it; disassembly and Traces keep the instruction's name.
export const emitOpcodes = (instructions: { name: string }[]): string => {
  if (instructions.length > 256) {
    throw new Error('Opcode is a uint8, but there are more instructions');
  }
  return formatGo(
    '// Code generated by tools/go/generate.ts from spec/data/machine.toml; DO NOT EDIT.\n' +
      'package generated\n\n' +
      "// Opcode is an instruction's index in Machine.Instruction.\n" +
      'type Opcode uint8\n\nconst (\n' +
      instructions
        .map(
          ({ name }, i) =>
            `Op${identifier(name)}${i === 0 ? ' Opcode = iota' : ''}\n`,
        )
        .join('') +
      ')\n',
  );
};

export const emitStandardLibraries = (
  sources: Record<string, string>,
): string =>
  formatGo(
    '// Code generated by tools/go/generate.ts from spec/stdlib/*.talk; DO NOT EDIT.\n' +
      'package generated\n\nvar StandardLibraries = map[string]string{\n' +
      Object.entries(sources)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(
          ([name, source]) =>
            `${JSON.stringify(name)}: ${JSON.stringify(source)},\n`,
        )
        .join('') +
      '}\n',
  );

// The Cost Model's formulas as compiled terms, with named measure and subject
// codes, so the Go Core evaluates a charge without parsing or lookups.
const goTerms = (list: readonly (readonly number[])[]) =>
  `[]CostTerm{${list.map(t => `{${t.join(', ')}}`).join(', ')}}`;
export const emitCostTerms = (model: CompiledCostModel): string =>
  formatGo(
    '// Code generated by tools/go/generate.ts from spec/data/costs.toml; DO NOT EDIT.\n' +
      'package generated\n\n' +
      '// CostTerm is one compiled Cost Model term: Factor * Measure(Subject) /\n' +
      '// Divisor, rounded up on its own. MeasureConstant is worth 1.\n' +
      'type CostTerm struct {\nMeasure, Subject uint8\nFactor, Divisor int64\n}\n\n' +
      'type CostRate struct {\nKey string\nFuel, Alloc []CostTerm\n}\n\n' +
      'type CostSize struct {\nOf string\nTerms []CostTerm\n}\n\n' +
      `const (\n${model.measures
        .map((name, i) => `Measure${identifier(name)} = ${i}\n`)
        .join('')})\n\n` +
      "// SubjectX1 is a Built-in's first argument; SubjectX1 + n - 1 is its nth.\n" +
      `const (\n${model.subjects
        .map((name, i) => `Subject${identifier(name)} = ${i}\n`)
        .join('')})\n\n` +
      `var CostRates = []CostRate{\n${model.rates
        .map(
          r =>
            `{${JSON.stringify(r.key)}, ${goTerms(r.fuel)}, ${goTerms(r.alloc)}},\n`,
        )
        .join('')}}\n\n` +
      `// CostRateIndex gives each Cost Model key's index in CostRates.\n` +
      `var CostRateIndex = map[string]int{\n${model.rates
        .map((r, i) => `${JSON.stringify(r.key)}: ${i},\n`)
        .join('')}}\n\n` +
      `var CostSizes = []CostSize{\n${model.sizes
        .map(s => `{${JSON.stringify(s.of)}, ${goTerms(s.terms)}},\n`)
        .join('')}}\n`,
  );

export const generateGoCatalogues = async (check: boolean): Promise<void> => {
  const sources: Record<string, string> = {};
  for (const name of [
    'text',
    'list',
    'map',
    'bytes',
    'json',
    'date',
    'units',
  ]) {
    sources[name] = await readFile(
      resolve(import.meta.dir, `../../spec/stdlib/${name}.talk`),
      'utf8',
    );
  }
  await writeOutput(
    resolve(import.meta.dir, '../../impl/go/internal/generated/stdlib.go'),
    emitStandardLibraries(sources),
    check,
    'bun run go:generate',
  );
  const reader = await readFile(
    resolve(import.meta.dir, '../../spec/session/inspect-reader.talk'),
    'utf8',
  );
  await writeOutput(
    resolve(import.meta.dir, '../../impl/go/internal/generated/session.go'),
    formatGo(
      '// Code generated by tools/go/generate.ts from spec/session/inspect-reader.talk; DO NOT EDIT.\npackage generated\nconst InspectReader = ' +
        JSON.stringify(reader) +
        '\n',
    ),
    check,
    'bun run go:generate',
  );
  await writeOutput(
    resolve(import.meta.dir, '../../impl/go/internal/generated/rates.go'),
    emitCostTerms(compileCostModel(costs)),
    check,
    'bun run go:generate',
  );
  await writeOutput(
    resolve(import.meta.dir, '../../impl/go/internal/generated/opcodes.go'),
    emitOpcodes(machine.instruction),
    check,
    'bun run go:generate',
  );
  for (const [name, data] of Object.entries({
    machine,
    costs,
    errors,
    diagnostics,
    limits,
    units,
    version,
    corpus,
    grammar,
    builtins: { builtin: stdlib.builtin },
  })) {
    await writeOutput(
      resolve(import.meta.dir, `../../impl/go/internal/generated/${name}.go`),
      emitCatalogue(name, data, name === 'builtins' ? 'stdlib' : name),
      check,
      'bun run go:generate',
    );
  }
};

if (import.meta.main) {
  if (Bun.argv.slice(2).some(arg => arg !== '--check')) {
    throw new Error('Usage: bun tools/go/generate.ts [--check]');
  }
  await generateGoCatalogues(Bun.argv.includes('--check'));
}
