import { resolve } from 'node:path';
import type { generateUnicodeData } from './generate';
import { formatGo, writeOutput } from '../go/output';

export const generateGoUnicode = async (
  data: ReturnType<typeof generateUnicodeData>,
  check: boolean,
): Promise<void> => {
  let source =
    '// Code generated by tools/unicode/generate.ts from pinned Unicode Data Files; DO NOT EDIT.\n' +
    '// Unicode data © Unicode, Inc.; see UNICODE-LICENSE.txt.\npackage generated\n\n' +
    'type PropertyRange[T any] struct { Start, End rune; Value T }\n\n';
  for (const [name, value] of Object.entries(data)) {
    const publicName = name[0]!.toUpperCase() + name.slice(1);
    if (typeof value === 'string') {
      source += `const ${publicName} = ${JSON.stringify(value)}\n`;
    } else if (Array.isArray(value)) {
      const type = typeof value[0]?.[2] === 'string' ? 'string' : 'int';
      source += `var ${publicName} = []PropertyRange[${type}]{\n`;
      for (const [start, end, property] of value) {
        source += `{${start}, ${end}, ${JSON.stringify(property)}},\n`;
      }
      source += '}\n';
    } else {
      const type =
        name === 'sourceHashes'
          ? 'map[string]string'
          : name === 'composition'
            ? 'map[int64]rune'
            : name === 'folding'
              ? 'map[rune]rune'
              : 'map[rune][]rune';
      source += `var ${publicName} = ${type}{\n`;
      for (const [key, entry] of Object.entries(value)) {
        source += `${name === 'sourceHashes' ? JSON.stringify(key) : key}: `;
        source += Array.isArray(entry)
          ? `{${entry.join(',')}},\n`
          : `${JSON.stringify(entry)},\n`;
      }
      source += '}\n';
    }
  }
  await writeOutput(
    resolve(import.meta.dir, '../../impl/go/internal/generated/unicode.go'),
    formatGo(source),
    check,
    'bun run unicode:generate',
  );
};
