// Writes the TextMate grammar from the Core's generated syntax tables and the
// stdlib Data File, so its word lists follow the Spec. `--check` fails instead
// of writing when the committed grammar is stale.
import { readFileSync, writeFileSync } from 'node:fs';
import { grammar, units } from '@odgn/northtalk';

const root = new URL('../../../', import.meta.url);
const output = new URL(
  '../syntaxes/northtalk.tmLanguage.json',
  import.meta.url,
);

type Builtin = { group: string; name: string };
const stdlib = Bun.TOML.parse(
  readFileSync(new URL('spec/data/stdlib.toml', root), 'utf8'),
) as { builtin: Builtin[] };

const reserved = new Set((grammar as { reserved: string[] }).reserved);
const follow = (grammar as { follow: string[] }).follow;

const words = (list: Iterable<string>) =>
  [...new Set(list)].sort((a, b) => b.length - a.length || (a < b ? -1 : 1));
const alternation = (list: Iterable<string>) => words(list).join('|');
const wordsRule = (name: string, list: Iterable<string>) => ({
  name,
  match: `(?<![A-Za-z0-9_])(?:${alternation(list)})(?![A-Za-z0-9_])`,
});
const take = (list: readonly string[]) => {
  for (const word of list) {
    if (!reserved.delete(word)) {
      throw new Error(`${word} is no longer a Reserved Word`);
    }
  }
  return list;
};

const constants = take(['false', 'it', 'me', 'nothing', 'true']);
const operators = take(['and', 'in', 'is', 'not', 'of', 'or']);
const control = take([
  'after',
  'catch',
  'else',
  'end',
  'exit',
  'finally',
  'for',
  'given',
  'if',
  'match',
  'offer',
  'pass',
  'repeat',
  'return',
  'then',
  'throw',
  'try',
  'until',
  'veto',
  'wait',
  'when',
  'where',
  'while',
]);
take(['on', 'function']);
// The remaining Reserved Words are statement words and separators.
const statements = [...reserved];
const operatorWords = follow.filter(word =>
  ['begins', 'contains', 'div', 'ends', 'matches', 'mod'].includes(word),
);
// Contextual words worth colouring wherever they stand, as the Playground does.
const contextual = [
  ...follow.filter(word => !operatorWords.includes(word)),
  'all',
  'any',
  'case',
  'each',
  'say',
];

const builtins = (group: (name: string) => boolean) =>
  stdlib.builtin.filter(b => group(b.group)).map(b => b.name);
const unitNames = units.flatMap(unit =>
  [unit.name, (unit as { plural?: string }).plural].filter(
    (name): name is string => !!name,
  ),
);
const unitFactor = String.raw`(?:${alternation(unitNames)})(?:\^[1-9][0-9]*)?`;
const unit = `(?:1/)?${unitFactor}(?:[*/]${unitFactor})*`;

const tmLanguage = {
  $schema:
    'https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json',
  name: 'NorthTalk',
  scopeName: 'source.northtalk',
  fileTypes: ['talk'],
  comment: 'Generated by tooling/vscode/tools/grammar.ts; do not edit.',
  patterns: [{ include: '#code' }],
  repository: {
    code: {
      patterns: [
        { include: '#comment' },
        { include: '#raw-text' },
        { include: '#interpolated-text' },
        { include: '#quoted-text' },
        { include: '#number' },
        { include: '#fallback' },
        { include: '#declaration' },
        { include: '#block-end' },
        { include: '#use' },
        { include: '#keywords' },
        { include: '#builtins' },
        { include: '#call' },
        { include: '#name' },
        { include: '#punctuation' },
      ],
    },
    comment: {
      name: 'comment.line.double-dash.northtalk',
      match: '--.*$',
    },
    'raw-text': {
      name: 'string.quoted.triple.northtalk',
      begin: '("{3,})',
      end: String.raw`(?<!")(\1)(?!")`,
      beginCaptures: {
        1: { name: 'punctuation.definition.string.begin.northtalk' },
      },
      endCaptures: {
        1: { name: 'punctuation.definition.string.end.northtalk' },
      },
    },
    'interpolated-text': {
      name: 'string.interpolated.northtalk',
      begin: '`',
      end: '`',
      beginCaptures: {
        0: { name: 'punctuation.definition.string.begin.northtalk' },
      },
      endCaptures: {
        0: { name: 'punctuation.definition.string.end.northtalk' },
      },
      patterns: [
        {
          name: 'constant.character.escape.northtalk',
          match: String.raw`\\(?:x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4}|u\{[0-9A-Fa-f]+\}|0(?![0-9])|[^0-9xu]|$)`,
        },
        {
          name: 'invalid.illegal.escape.northtalk',
          match: String.raw`\\.?`,
        },
        {
          name: 'meta.embedded.line.northtalk',
          contentName: 'source.northtalk',
          begin: String.raw`\$\{`,
          end: String.raw`\}`,
          beginCaptures: {
            0: { name: 'punctuation.section.embedded.begin.northtalk' },
          },
          endCaptures: {
            0: { name: 'punctuation.section.embedded.end.northtalk' },
          },
          patterns: [{ include: '#braces' }, { include: '#code' }],
        },
      ],
    },
    braces: {
      begin: String.raw`\{`,
      end: String.raw`\}`,
      beginCaptures: { 0: { name: 'punctuation.section.braces.northtalk' } },
      endCaptures: { 0: { name: 'punctuation.section.braces.northtalk' } },
      patterns: [{ include: '#braces' }, { include: '#code' }],
    },
    'quoted-text': {
      name: 'string.quoted.double.northtalk',
      begin: '"',
      end: '"|$',
      beginCaptures: {
        0: { name: 'punctuation.definition.string.begin.northtalk' },
      },
      endCaptures: {
        0: { name: 'punctuation.definition.string.end.northtalk' },
      },
    },
    number: {
      match: String.raw`(?<![A-Za-z0-9_])(0x[0-9A-Fa-f]+|[0-9]+(?:\.[0-9]+)?)(?:[ \t]*(${unit}))?(?![A-Za-z0-9_])`,
      captures: {
        1: { name: 'constant.numeric.northtalk' },
        2: { name: 'keyword.other.unit.northtalk' },
      },
    },
    // `any message` after `on`, `end` or `pass` names the Fallback Handler
    // (ADR 0063); `on any x` is still a Handler named `any`.
    fallback: {
      match: String.raw`(?<![A-Za-z0-9_])(?:(on)|(end)|(pass))[ \t]+(any)[ \t]+(message)(?![A-Za-z0-9_])`,
      captures: {
        1: { name: 'storage.type.function.northtalk' },
        2: { name: 'keyword.control.northtalk' },
        3: { name: 'keyword.other.northtalk' },
        4: { name: 'keyword.other.northtalk' },
        5: { name: 'keyword.other.northtalk' },
      },
    },
    declaration: {
      match: String.raw`(?<![A-Za-z0-9_])(?:(private)[ \t]+)?(on|function)[ \t]+([A-Za-z_][A-Za-z0-9_]*)`,
      captures: {
        1: { name: 'storage.modifier.northtalk' },
        2: { name: 'storage.type.function.northtalk' },
        3: { name: 'entity.name.function.northtalk' },
      },
    },
    'block-end': {
      patterns: [
        {
          match: String.raw`(?<![A-Za-z0-9_])(end)[ \t]+(${alternation(control)}|tell)(?![A-Za-z0-9_])`,
          captures: {
            1: { name: 'keyword.control.northtalk' },
            2: { name: 'keyword.control.northtalk' },
          },
        },
        {
          match: String.raw`(?<![A-Za-z0-9_])(end)[ \t]+([A-Za-z_][A-Za-z0-9_]*)(?![A-Za-z0-9_])`,
          captures: {
            1: { name: 'keyword.control.northtalk' },
            2: { name: 'entity.name.function.northtalk' },
          },
        },
      ],
    },
    // `use a, b from library as alias`
    use: {
      begin: String.raw`^[ \t]*(use)(?![A-Za-z0-9_])`,
      end: '$',
      beginCaptures: { 1: { name: 'keyword.other.import.northtalk' } },
      patterns: [
        { include: '#comment' },
        {
          match: String.raw`(?<![A-Za-z0-9_])(from|as)[ \t]+([A-Za-z_][A-Za-z0-9_]*)(?![A-Za-z0-9_])`,
          captures: {
            1: { name: 'keyword.other.import.northtalk' },
            2: { name: 'entity.name.namespace.northtalk' },
          },
        },
        { include: '#name' },
        { include: '#punctuation' },
      ],
    },
    keywords: {
      patterns: [
        wordsRule('constant.language.northtalk', constants),
        wordsRule('keyword.control.northtalk', control),
        wordsRule('keyword.operator.word.northtalk', [
          ...operators,
          ...operatorWords,
        ]),
        wordsRule('storage.modifier.northtalk', [
          'constant',
          'private',
          'script',
          'variable',
        ]),
        wordsRule('keyword.other.northtalk', [...statements, ...contextual]),
      ],
    },
    builtins: {
      patterns: [
        wordsRule(
          'support.constant.northtalk',
          builtins(group => group === 'constants'),
        ),
        wordsRule(
          'support.function.builtin.northtalk',
          builtins(group => group !== 'constants'),
        ),
      ],
    },
    call: {
      match: String.raw`([A-Za-z_][A-Za-z0-9_]*)(?=\()`,
      captures: { 1: { name: 'entity.name.function.call.northtalk' } },
    },
    name: {
      name: 'variable.other.northtalk',
      match: '[A-Za-z_][A-Za-z0-9_]*',
    },
    punctuation: {
      patterns: [
        {
          name: 'keyword.operator.possessive.northtalk',
          match: "'s(?![A-Za-z0-9_])",
        },
        {
          name: 'keyword.operator.northtalk',
          match: String.raw`\.\.\.|\.\.|<>|<=|>=|<<|>>|[&=<>+\-*/^]`,
        },
        { name: 'punctuation.separator.northtalk', match: '[,:]' },
        {
          name: 'punctuation.section.brackets.northtalk',
          match: String.raw`[()\[\]{}]`,
        },
      ],
    },
  },
};

const text = `${JSON.stringify(tmLanguage, null, 2)}\n`;
if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== text) {
    throw new Error(
      'syntaxes/northtalk.tmLanguage.json is stale; run bun run --cwd tooling/vscode grammar:generate',
    );
  }
} else {
  writeFileSync(output, text);
}
