#!/usr/bin/env bun
// Tooling catalogue plus Spec tags/properties, copied for browser workers.
import catalogue from '../../tooling/stack/lints.toml';
import grammar from '../../spec/data/grammar.toml';
import { builtins } from '../../impl/ts/src/generated/syntax';
import { resolve } from 'node:path';

type Entry = {
  beginner: 'off' | 'hint' | 'warning';
  fix?: string;
  flags: string;
  id: string;
  message: string;
  standard: 'off' | 'hint' | 'warning';
  status: 'implemented' | 'planned';
};
const entries = catalogue.lint as Entry[];
const ids = new Set<string>();
for (const entry of entries) {
  if (
    !/^[a-z]+(?:-[a-z]+)*$/.test(entry.id) ||
    ids.has(entry.id) ||
    !['off', 'hint', 'warning'].includes(entry.beginner) ||
    !['off', 'hint', 'warning'].includes(entry.standard) ||
    !['implemented', 'planned'].includes(entry.status) ||
    !entry.flags ||
    !entry.message
  ) {
    throw new Error(`Invalid Lint catalogue entry: ${entry.id}`);
  }
  ids.add(entry.id);
}
const threshold = catalogue.settings.long_join_body_lines as number;
if (!Number.isInteger(threshold) || threshold < 0) {
  throw new Error('The Join line threshold must be a nonnegative integer');
}
const content =
  '// Generated by tools/lints/generate.ts. Do not edit.\n' +
  `export const lintCatalogue = ${JSON.stringify(entries, null, 2)} as const;\n` +
  `export const longJoinBodyLines = ${threshold};\n` +
  `export const advancedTags = ${JSON.stringify(grammar.advanced, null, 2)} as const;\n` +
  `export const properties = ${JSON.stringify(grammar.properties, null, 2)} as const;\n` +
  `export const builtins = ${JSON.stringify(
    builtins.map(({ name, kind }) => ({ name, kind })),
    null,
    2,
  )} as const;\n`;
const path = resolve(
  import.meta.dir,
  '../../tooling/stack/src/generated/lints.ts',
);
if (process.argv.includes('--check')) {
  if (
    !(await Bun.file(path).exists()) ||
    (await Bun.file(path).text()) !== content
  ) {
    throw new Error('Lint tables are stale; run bun run lints:generate');
  }
} else {
  await Bun.write(path, content);
}
