#!/usr/bin/env bun
// Browser-safe copies of the normative syntax lists; no Host TOML loader.
import grammar from '../../spec/data/grammar.toml';
import catalogue from '../../spec/data/units.toml';
import { resolve } from 'node:path';

const calendar = new Set(
  (catalogue.kind as { calendar?: boolean; name: string }[])
    .filter(kind => kind.calendar)
    .map(kind => kind.name),
);
const syntax = {
  reserved: grammar.reserved as string[],
  chunk: grammar.chunk as { plural: string; singular: string }[],
  ordinals: grammar.ordinals as string[],
  properties: grammar.properties as string[],
  follow: grammar.follow as string[],
  decision: (grammar.decision as { name: string }[]).map(({ name }) => name),
  text_patterns: grammar.text_patterns as {
    anchors: string[];
    classes: string[];
    keywords: string[];
  },
  binary_patterns: grammar.binary_patterns as {
    byte_orders: string[];
    integer_types: string[];
    size_units: string[];
  },
};
const units = (
  catalogue.unit as { kind: string; name: string; plural?: string }[]
).map(({ kind, name, plural }) => ({
  name,
  ...(plural ? { plural } : {}),
  calendar: calendar.has(kind),
}));
const content =
  '// Generated by tools/syntax/generate.ts from Spec Data Files. Do not edit.\n' +
  `export const grammar = ${JSON.stringify(syntax, null, 2)};\n` +
  `export const units = ${JSON.stringify(units, null, 2)};\n`;
const path = resolve(import.meta.dir, '../../src/generated/syntax.ts');
if (process.argv.includes('--check')) {
  if (
    !(await Bun.file(path).exists()) ||
    (await Bun.file(path).text()) !== content
  ) {
    throw new Error('Syntax tables are stale; run bun run syntax:generate');
  }
} else {
  await Bun.write(path, content);
}
