#!/usr/bin/env bun
// Browser-safe copies of the normative syntax lists and instruction set; no
// Host TOML loader.
import grammar from '../../spec/data/grammar.toml';
import catalogue from '../../spec/data/units.toml';
import diagnostics from '../../spec/data/diagnostics.toml';
import stdlib from '../../spec/data/stdlib.toml';
import machine from '../../spec/data/machine.toml';
import costs from '../../spec/data/costs.toml';
import errors from '../../spec/data/errors.toml';
import limits from '../../spec/data/limits.toml';
import version from '../../spec/data/version.toml';
import { resolve } from 'node:path';
import { parseSource } from '../../src/parser';

// Parse the catalogue's call notation with the Core grammar, including defaults
// containing nested expressions or commas in text. Constants have no contract.
const contract = (call: string) => {
  const open = call.indexOf('(');
  if (open < 0 || !call.endsWith(')')) {
    return undefined;
  }
  const parsed = parseSource(
    `function signature ${call.slice(open + 1, -1)}\nend signature`,
  );
  if (parsed.error) {
    throw new Error(`Invalid function catalogue signature: ${call}`, {
      cause: parsed.error,
    });
  }
  const declaration = parsed.tree.children.find(
    child => child.kind === 'node',
  )!;
  if (declaration.kind !== 'node') {
    throw new Error(`Missing signature declaration: ${call}`);
  }
  const fn = declaration.children.find(
    child => child.kind === 'node' && child.rule === 'Function',
  )!;
  if (fn.kind !== 'node') {
    throw new Error(`Missing signature function: ${call}`);
  }
  const parameters = fn.children.filter(
    child => child.kind === 'node' && child.rule === 'Parameter',
  );
  return {
    required: parameters.filter(
      parameter =>
        parameter.kind === 'node' &&
        !parameter.children.some(
          child => child.kind === 'node' && child.rule === 'Expression',
        ),
    ).length,
    total: parameters.length,
  };
};

const calendar = new Set(
  (catalogue.kind as { calendar?: boolean; name: string }[])
    .filter(kind => kind.calendar)
    .map(kind => kind.name),
);
const syntax = {
  reserved: grammar.reserved as string[],
  chunk: grammar.chunk as { plural: string; singular: string }[],
  ordinals: grammar.ordinals as string[],
  properties: grammar.properties as string[],
  follow: grammar.follow as string[],
  decision: (grammar.decision as { name: string }[]).map(({ name }) => name),
  text_patterns: grammar.text_patterns as {
    anchors: string[];
    classes: string[];
    keywords: string[];
  },
  binary_patterns: grammar.binary_patterns as {
    byte_orders: string[];
    integer_types: string[];
    size_units: string[];
  },
};
const units = (
  catalogue.unit as { kind: string; name: string; plural?: string }[]
).map(({ kind, name, plural }) => ({
  name,
  ...(plural ? { plural } : {}),
  kind,
  calendar: calendar.has(kind),
}));
// The Kind order that a Compound Unit's factors print in.
const unitKinds = (catalogue.kind as { name: string }[]).map(
  ({ name }) => name,
);
const content =
  '// Generated by tools/syntax/generate.ts from Spec Data Files. Do not edit.\n' +
  `export const grammar = ${JSON.stringify(syntax, null, 2)};\n` +
  `export const units = ${JSON.stringify(units, null, 2)};\n` +
  `export const unitKinds = ${JSON.stringify(unitKinds, null, 2)};\n` +
  `export const diagnosticCodes = ${JSON.stringify(
    (diagnostics.diagnostic as { code: string }[]).map(row => row.code),
    null,
    2,
  )} as const;\n` +
  `export const builtins = ${JSON.stringify(
    (stdlib.builtin as { call: string; group: string; name: string }[]).map(
      ({ call, group, name }) => ({
        name,
        kind: group === 'constants' ? 'constant' : 'function',
        ...(group === 'constants' ? {} : { contract: contract(call) }),
      }),
    ),
    null,
    2,
  )} as const;\n` +
  `export const libraryExports = ${JSON.stringify(
    (stdlib.export as { call: string; library: string; name: string }[]).map(
      ({ call, library, name }) => ({
        library,
        name,
        kind: call.startsWith(name + '(') ? 'function' : 'constant',
        ...(call.startsWith(name + '(') ? { contract: contract(call) } : {}),
      }),
    ),
    null,
    2,
  )} as const;\n`;
// The instruction set, for the lowering and the canonical disassembly.
type Instruction = {
  cost: string;
  jumps?: number;
  name: string;
  operands: string[];
  pops: number | string;
  pushes: number | string;
  suspends: boolean;
};
const machineContent =
  '// Generated by tools/syntax/generate.ts from Spec Data Files. Do not edit.\n' +
  `export const instructions = ${JSON.stringify(
    (machine.instruction as Instruction[]).map(
      ({ name, operands, pops, pushes, jumps, suspends, cost }) => ({
        name,
        cost,
        operands,
        pops,
        pushes,
        ...(jumps === undefined ? {} : { jumps }),
        suspends,
      }),
    ),
    null,
    2,
  )} as const;\n` +
  `export const languageVersion = ${JSON.stringify(version.language)};\n` +
  `export const errorMessages = ${JSON.stringify(
    Object.fromEntries(
      (errors.error as { code: string; message: string }[]).map(
        ({ code, message }) => [code, message],
      ),
    ),
    null,
    2,
  )};\n` +
  `export const limitDefaults = ${JSON.stringify(
    Object.fromEntries(
      (limits.limit as { default: number; ts: string }[]).map(
        ({ ts, default: value }) => [ts, value],
      ),
    ),
    null,
    2,
  )};\n` +
  `export const costModel = ${JSON.stringify(
    {
      version: costs.version as number,
      sizes: Object.fromEntries(
        (costs.size as { of: string; size: string }[]).map(({ of, size }) => [
          of,
          size,
        ]),
      ),
      rates: Object.fromEntries(
        (costs.rate as { alloc?: string; fuel: string; key: string }[]).map(
          ({ key, fuel, alloc }) => [key, { fuel, alloc: alloc ?? '0' }],
        ),
      ),
    },
    null,
    2,
  )};\n`;
const outputs = [
  [resolve(import.meta.dir, '../../src/generated/syntax.ts'), content],
  [resolve(import.meta.dir, '../../src/generated/machine.ts'), machineContent],
] as const;
for (const [path, text] of outputs) {
  if (process.argv.includes('--check')) {
    if (
      !(await Bun.file(path).exists()) ||
      (await Bun.file(path).text()) !== text
    ) {
      throw new Error('Syntax tables are stale; run bun run syntax:generate');
    }
  } else {
    await Bun.write(path, text);
  }
}
